name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout project
        uses: actions/checkout@v3
      - name: composer install
        run: composer install
      - name: run unit tests
        run: ./vendor/bin/phpunit
